### ISSUE TITLE
Create Next Edge (Web API) handlers

### ISSUE THREAD

**Issue by lkostrowski** [saleor/app-sdk#171]
Currently app-sdk has only Next.js node runtime handlers.

We can expose handlers built for Edge runtime, that will open Edge Config and other runtimes like Deno, Cloudflare

**Comment by JannikZed** [comment]
To bring more priority into this issue: synchronous webhooks would really benefit from this change, as things need to be really fast and we could skip the cold-startup times with edge functions.

**Comment by lkostrowski** [comment]
We are experimenting with edge runtime in the Adyen app
