### ISSUE TITLE
`RoutePropagator` should differentiate between `push` and `replace`

### ISSUE THREAD

**Issue by mmiszy** [saleor/app-sdk#248]
### What I'm trying to achieve

When using `router.replace(…)` in apps, `RoutePropagator` still propagates it as if `router.push(…)` was called. This leads to awkward situations.

### Describe a proposed solution

`router.replace(…)` should trigger a different event or payload than `router.push(…)`.
Similarly, clicking on a `<Link href="…">` should trigger a different event or payload than `<Link replace href="…">`

Blocked by https://github.com/vercel/next.js/pull/50355

**Comment by lkostrowski** [comment]
Since Vercel rejected, I'm also closing this until we find a better way to do that
