### ISSUE TITLE
Build Saleor app with SST

### ISSUE THREAD

**Issue by ivanakcheurov** [saleor/app-sdk#274]
### What I'm trying to achieve
Create a Saleor app built on top of [SST](https://sst.dev/) (as opposed to Next.js)
…

### Describe a proposed solution
I need 1 [helper function/class](https://github.com/saleor/saleor-app-sdk/blob/5c56cf566d2cc6e4a075c8c619f174fa43aad6c9/docs/saleor-webhook.md?plain=1#L65) that creates an [SST's ApiGateway function handler](https://docs.sst.dev/apis#add-the-handler).

Perhaps other helper functions are needed e.g. for installation of the Saleor app, serving its manifest, etc.
...

### Other solutions I've tried and won't work

…

**Comment by lkostrowski** [comment]
Hey

At the moment majority of app-sdk utilities rely on Next.js API.

We want to support another tech stack in the future, but we still need to get it on the roadmap.

Saleor Webhooks utilities (https://github.com/saleor/saleor-app-sdk/blob/5c56cf566d2cc6e4a075c8c619f174fa43aad6c9/src/handlers/next/saleor-webhooks/saleor-webhook.ts)
rely on this https://github.com/saleor/saleor-app-sdk/blob/5c56cf566d2cc6e4a075c8c619f174fa43aad6c9/src/handlers/next/process-protected-handler.ts heavily

I suggest you copy-paste logic related to the verification request from Saleor until there is an official implementation
